language: c
before_script:
  - git clone https://github.com/asdf-vm/asdf.git asdf
  - . asdf/asdf.sh
script:
  - asdf plugin-add tflint https://github.com/RykHawthorn/asdf-tflint.git
  - asdf list-all tflint
  - asdf plugin-test tflint ./ 'tflint --version'
os:
  - linux
  - osx
